---
title: "ESM_237_HW_1"
author: "Camila Bobroff"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, load packages}
library(tidyverse)
library(janitor)
library(tseries)
library(lubridate)
```

```{r, read in the data}

data <- read_csv("data_monthly.csv") %>% 
  clean_names()

temp <- data %>%
  select(date, tmax, tmin)
  
precip <- data %>% 
  select(date, prcp)

```

```{r, data exploration}
# Convert to timeseries data

maxtemp_ts <- ts(temp$tmax, frequency = 365, start = c(4/15/69, 1))
plot(maxtemp_ts)

mintemp_ts <- ts(temp$tmin, frequency = 365, start = c(4/15/69, 1))
plot(mintemp_ts)

precip_ts <- ts(precip$prcp, frequency = 365, start = c(4/15/69, 1))
plot(precip_ts)

# Decompose to explore data further

# maxtemp_dc <- decompose(maxtem_ts)
# 
# library(zoo)
# decompose(na.StructTS(maxtemp_ts))
# maxtemp_dc <- decompose(maxtemp_ts)

```

```{r, exploratory plots}
maxtemp_plot <- temp %>% 
  ggplot(aes(x = date, y = tmax, group = 1)) +
  labs(y = "Maximum Monthly Temperature (°F)", x = "Date") +
  geom_line()

maxtemp_plot

mintemp_plot <- temp %>%
  ggplot(aes(x = date, y = tmin, group = 1)) +
  geom_line()

mintemp_plot

prcp_plot <- precip %>%
  ggplot(aes(x = date, y = prcp, group = 1)) +
  geom_line()

prcp_plot
```

```{r, monthly average temp/extremes - summer}

# Filter for summer months only
temp_summer <- temp %>% 
  separate(date, sep = "-", into = c("year", "month")) %>% 
  filter(month == "06" | month == "07" | month == "08") %>% 
  unite("date", year, month, sep = "-")

temp_summer_plotdf <- temp_summer %>%
  separate(date, sep = "-", into = c("year", "month")) %>% 
  group_by(year) %>% 
  summarize(tmax_ave = mean(tmax), tmin_ave = mean(tmin)) 

# as.numeric(temp_summer_plotdf$year)
# 
# temp_summer_plot = ggplot(temp_summer_plotdf, aes(x = date, y = tmin_ave)) +
#   geom_point(col = "blue") + 
#   scale_y_continuous(limits = c(min(temp_summer_plotdf$tmin_ave), max(temp_summer_plotdf$tmax_ave))) +
#   geom_point(data=temp_summer_plotdf, aes(x=date, y = tmin_ave), col="blue")

# temp_summer_plot

maxtemp_summer <- temp_summer_plotdf %>% 
  select(year, tmax_ave)

linear_tmax <- lm(year~tmax_ave, data = maxtemp_summer)
coeff = coefficients(linear_tmax)
summary(linear_tmax)
# Adjusted R-squared: 0.02808
# p-value: 0.1291

plot(maxtemp_summer,
          pch = 19,
          col = "red",
          xlab = "Year",
          ylab = "Average Monthly Maximum Summer Temperature (°F)")
abline(linear_tmax)


mintemp_summer <- temp_summer_plotdf %>% 
  select(year, tmin_ave)

linear_tmin <- lm(year~tmin_ave, data = mintemp_summer)
coeff = coefficients(linear_tmin)
summary(linear_tmin)
# Adjusted R-squared: 0.6067
# p-value: <.0001

plot(mintemp_summer,
          pch = 19,
          col = "blue",
          xlab = "Year",
          ylab = "Average Monthly Minimum Summer Temperature (°F)")
abline(linear_tmin)

# EXTREME MAX Filter for summer months only
ext_summer <- data %>% 
  select(date, emxt) %>% 
  separate(date, sep = "-", into = c("year", "month")) %>% 
  filter(month == "06" | month == "07" | month == "08") %>% 
  unite("date", year, month, sep = "-")

ext_summer_plotdf <- ext_summer %>%
  separate(date, sep = "-", into = c("year", "month")) %>% 
  group_by(year) %>% 
  summarize(emxt = max(emxt)) %>% 
  na.omit()

plot(ext_summer_plotdf,
          pch = 19,
          col = "red",
          xlab = "Year",
          ylab = "Extreme Maximum Summer Temperatures (°F)")

linear_ext <- lm(year~emxt, data = ext_summer_plotdf)
coeff = coefficients(linear_ext)
summary(linear_ext)
# Adjusted R-squared: 0.01099
# P-value: .2218

# EXTREME MIN Filter for summer months only
extmin_summer <- data %>% 
  select(date, emnt) %>% 
  separate(date, sep = "-", into = c("year", "month")) %>% 
  filter(month == "06" | month == "07" | month == "08") %>% 
  unite("date", year, month, sep = "-")

extmin_summer_plotdf <- extmin_summer %>%
  separate(date, sep = "-", into = c("year", "month")) %>% 
  group_by(year) %>% 
  summarize(emnt = min(emnt)) %>% 
  na.omit()

plot(extmin_summer_plotdf,
          pch = 19,
          col = "blue",
          xlab = "Year",
          ylab = "Extreme Minimum Summer Temperatures (°F)")

linear_extmin <- lm(year~emnt, data = extmin_summer_plotdf)
coeff = coefficients(linear_extmin)
summary(linear_extmin)
# Adjusted R-sqaure: 0.399
# p-value: <.0001

```

```{r, winter precipitation}
# Filter for winter months only

precip_winter <- precip %>% 
  separate(date, sep = "-", into = c("year", "month")) %>% 
  filter(month == "12" | month == "01" | month == "02") %>% 
  unite("date", year, month, sep = "-")

precip_winter_plotdf <- precip_winter %>%
  separate(date, sep = "-", into = c("year", "month")) %>% 
  group_by(year) %>% 
  summarize(prcp = mean(prcp)) 

plot(precip_winter_plotdf,
          pch = 19,
          col = "black",
          xlab = "Year",
          ylab = "Average Winter Precipitation (inches)")

linear_prcp <- lm(year~prcp, data = precip_winter_plotdf)
coeff = coefficients(linear_prcp)
summary(linear_prcp)
# Adjusted R-squared: -.009105
# p-value: 0.4552

# Filter for winter months only

ext_precip_winter <- data %>%
  select(date, emxp) %>% 
  separate(date, sep = "-", into = c("year", "month")) %>% 
  filter(month == "12" | month == "01" | month == "02") %>% 
  unite("date", year, month, sep = "-")

extprecip_winter_plotdf <- ext_precip_winter %>%
  separate(date, sep = "-", into = c("year", "month")) %>% 
  group_by(year) %>% 
  summarize(emxp = max(emxp)) 

plot(extprecip_winter_plotdf,
          pch = 19,
          col = "black",
          xlab = "Year",
          ylab = "Maximum Winter Precipitation (inches)")

linear_extprcp <- lm(year~emxp, data = extprecip_winter_plotdf)
coeff = coefficients(linear_extprcp)
summary(linear_extprcp)
# Adjusted R-squared: -.01493
# p-value: 0.5902
```


